import { PaginationList } from "./paginationList";

export type Employee = {
  id?: string;
  identityNumber?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  description?: string;
  birthday?: string;
  genderId?: string;
  genderValue?: string;
  maritalStatusId?: string;
  maritalStatusValue?: string;
  hiringDate?: string;
  department?: string;
  workingStatusId?: string;
  workingStatusValue?: string;
  hiringSalary?: number;
  userId?: string;
  workerNumber?: string;
  companyId?: string;
  departmentId?: string;
  managerId?: string;
  assistantId?: string;
  jobTitleId?: string;
  jobTitleValue?: string;
  phoneNumber?: string;
  phoneNumberWork?: string;
  phoneNumberHome?: string;
  emailAddress?: string;
  secondaryEmailAddress?: string;
  assistantPhoneNumber?: string;
  positionId?: number;
  educationalStatusId?: string;
  educationalStatusValue?: string;
  school?: string;
  departmentOfEducation?: string;
  graduationDate?: string;
  companyName?: string;
  departmentName?: string;
  employmentStartDate?: string;
  dateOfLeaving?: string;
  externalManagerId?: string;
  externalManagerFullName?: string;
  bloodGroupId?: string;
  professionId?: string;
  socialSecurityStatusId?: string;
  healthPolicyId?: string;
  employmentLawId?: string;
  workTypeId?: string;
  professionCode?: string;
  enoctaNumber?: string;
  mealCardNumber?: string;
  projectInformation?: string;
  iban?: string;
  cumulativeIncomeTaxBase?: string;
  bloodGroupValue?: string;
  professionValue?: string;
  healthPolicyValue?: string;
  healthPolicyNumber?: string;
  socialSecurityStatusValue?: string;
  employmentLawValue?: string;
  workTypeValue?: string;
  homeAddress?: string;
  workLocationId?: string;
  martialStatusValue?: string;
  emergencyContactPerson?: string;
  emergencyContactDegree?: string;
  emergencyContactPhoneNumber?: string;
  positionName?: string;
  recruitmentSourceId?: string;
  recruitmentSourceValue?: string;
  reference?: string;
  reasonOfLeaving?: string;
  leavingDescription?: string;
  leavingCode?: string;
  managerFullName?: string;
  assistantFullName?: string;
  workLocationValue?: string;
};

export type PersonalInformation = {
  userId?: string;
  identityNumber?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  description?: string;
  birthday?: string;
  genderId?: string;
  maritalStatusId?: string;
  bloodGroupId?: string;
  professionId?: string;
  healthPolicyId?: string;
  socialSecurityStatusId?: string;
  workTypeId?: string;
  hiringSalary?: string;
  professionCode?: string;
  enoctaNumber?: string;
  mealCardNumber?: string;
  healthPolicyNumber?: string;
  iban?: string;
  genderValue?: string;
  maritalStatusValue?: string;
  bloodGroupValue?: string;
  professionValue?: string;
  socialSecurityStatusValue?: string;
  healthPolicyValue?: string;
};

export type ManagerPersonalInformation = {
  userId?: string;
  identityNumber?: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  description?: string;
  birthday?: string;
  genderId?: string;
  genderValue?: string;
  maritalStatusId?: string;
  maritalStatusValue?: string;
  bloodGroupId?: string;
  bloodGroupValue?: string;
  professionId?: string;
  socialSecurityStatusId?: string;
  healthPolicyId?: string;
  employmentLawId?: string;
  workTypeId?: string;
  hiringSalary?: string;
  professionCode?: string;
  enoctaNumber?: string;
  mealCardNumber?: string;
  projectInformation?: string;
  iban?: string;
  cumulativeIncomeTaxBase?: string;
  professionValue?: string;
  healthPolicyValue?: string;
  healthPolicyNumber?: string;
  socialSecurityStatusValue?: string;
  employmentLawValue?: string;
  workTypeValue?: string;
};

export interface EmployeeCardProps {
  avatar: string;
  firstName?: string;
  lastName?: string;
  departmentName: string;
}

export type ContactInformation = {
  userId?: string;
  phoneNumber?: string;
  phoneNumberWork?: string;
  phoneNumberHome?: string;
  emailAddress?: string;
  secondaryEmailAddress?: string;
  emergencyContactPerson?: string;
  emergencyContactDegree?: string;
  emergencyContactPhoneNumber?: string;
  homeAddress?: string;
};

export type BusinessInformation = {
  userId?: string;
  companyId?: string;
  departmentId?: string;
  positionId?: string;
  managerId?: string;
  externalManagerId?: string;
  assistantId?: string;
  hiringDate?: string;
  workingStatusId?: string;
  workLocationId?: string;
  workerNumber?: string;
  companyName?: string;
  departmentName?: string;
  positionName?: string;
  assistantPhoneNumber?: string;
  managerFullName?: string;
  externalManagerFullName?: string;
  assistantFullName?: string;
  workingStatusValue?: string;
  workLocationValue?: string;
};

export type ManagerBusinessInformation = {
  userId?: string;
  companyId?: string;
  departmentId?: string;
  positionId?: string;
  managerId?: string;
  externalManagerId?: string;
  assistantId?: string;
  jobTitleId?: string;
  hiringDate?: string;
  workingStatusId?: string;
  workLocationId?: string;
  workerNumber?: string;
  recruitmentSourceId?: string;
  reference?: string;
  reasonOfLeaving?: string;
  dateOfLeaving?: string;
  leavingDescription?: string;
  leavingCode?: string;
  jobTitleValue?: string;
  companyName?: string;
  departmentName?: string;
  positionName?: string;
  assistantPhoneNumber?: string;
  managerFullName?: string;
  externalManagerFullName?: string;
  assistantFullName?: string;
  workingStatusValue?: string;
  recruitmentSourceValue?: string;
  workLocationValue?: string;
};

export interface EmployeeStateProps {
  employee: PaginationList<Employee>;
  employeeCardList: EmployeeCardProps[];
  loading: boolean;
  loadingData: boolean;
  employeeDetail: Employee | null;
  personal: PersonalInformation | null;
  personalManager: ManagerPersonalInformation | null;
  updatedPersonal: ManagerPersonalInformation | null;
  contact: ContactInformation | null;
  updatedContact: ContactInformation | null;
  business: BusinessInformation | null;
  businessManager: ManagerBusinessInformation | null;
  updatedBusiness: ManagerBusinessInformation | null;
  error: object | string | null;
  addedEmployee: object | null;
  deletedEmployee: Employee | null;
  updatedEmployee: Employee | null;
}
